dist: bionic
deploy:
  provider: pypi
  user: __token__
  password:
    secure: cS1FoL6UYCdlsvujfknEbNUAibBEY4IrzujSIITdTCXFaobkxtG8SAXb84b7+DhhtlSW2nX5roIByWKb6Yd9UY7c7Hjm9e2oVA70GSd37+yNOz/YkkhxkwjgzP8AOipIqD9h/UScY8nNvOs+5+2oa99AcQ6YEaK5lyc60P48EDcIBY+TusrctObXweBF/2uq60PH58oX+UU8I9GFTUKgxEEGsFCoCrPaIXOuKCdk269L+73Wdp2Jx8wxeGPxzvUn1kpxjjYp48vXrr0OZTQHJMZcupue5GcRpQkZJPhNUMGyiqySuxv8j9U2XgzVaX8wEo6hTuHQ1TDfnxe7sye5LWcObxIVOzGNVc7mu7dRVn4VzcR7oy6BYrG6XDLn6SzMElPAuQkqKvBv6n/mwlW2uhDvouI9qYyZmK4ddGK1ddVoLGQf1nme8OyFeetacaqbePfq9XJGAi9buMPQrN5Xe57JnW2s0Cd8foxTaEa74LEMZqEsBhOIwJEgfTZFrCu8ODP+mcByWPRpVkqoPcEjNs2uwNkU+fryVe0+W23/5Rh3dlHbszY3e3Vt/ce3IQSK6hbW9u/jg2/OnhMHKI7Iw2z/beE4Isfw9ZG/1qsKuPaN9YO7y62MEVLkegF1YPjqmx647vGd6/cdiDpaz+NNbjYOjupQ1MOKzWHzZsKdiA0=
  on:
    tags: true
    condition: $RELEASER = "1"
language: python
git:
  submodules: true
addons:
  apt:
    packages:
    - build-essential
    - git
    - python
    - python-pip
    - python-virtualenv
    - libboost-all-dev
matrix:
  include:
  - os: linux
    env: DEBIAN_FRONTEND=noninteractive
    python: '3.6'
  - os: linux
    env: DEBIAN_FRONTEND=noninteractive
    python: '3.7'
  - os: linux
    env: DEBIAN_FRONTEND=noninteractive RELEASER=1
    python: '3.8'
  - os: linux
    env: DEBIAN_FRONTEND=noninteractive
    python: pypy3
  - os: osx
    env: CPYTHON_VERSION=3.6.8 PYTHON_PATH=/usr/local/bin/python3.6
    language: generic
  - os: osx
    env: CPYTHON_VERSION=3.7.6 PYTHON_PATH=/usr/local/bin/python3.7
    language: generic
  - os: osx
    env: CPYTHON_VERSION=3.8.1 PYTHON_PATH=/usr/local/bin/python3.8
    language: generic
  - os: osx
    env: PYPY=1 PYTHON_PATH=~/pypy3.6-v7.3.0-osx64/bin/pypy3
    language: generic
install:
- |
  case $TRAVIS_OS_NAME in
    linux)
      sudo pip install pipenv;
      pipenv install --python `which python` --skip-lock;
      ;;
    osx)
      brew update;
      brew install boost;
      pip install pipenv;
      ulimit -n 1200;
      pwd;
      if [ ! -z "$PYPY" ]; then
        cd ~;
        curl -s -L "https://bitbucket.org/pypy/pypy/downloads/pypy3.6-v7.3.0-osx64.tar.bz2" | tar xvj;
        cd $TRAVIS_BUILD_DIR;
      else
        curl -s -L "https://www.python.org/ftp/python/$CPYTHON_VERSION/python-$CPYTHON_VERSION-macosx10.9.pkg" --output python.pkg;
        sudo installer -pkg python.pkg -target /;
      fi
      pipenv install --python "$PYTHON_PATH" --skip-lock;
      ;;
    esac
script:
- pipenv run pip install pytest numpy
- pipenv run python setup.py install
- pipenv run pytest --verbose test.py
